In [ ]:
import numpy as np
import pandas as pd
from textblob import TextBlob
import plotly.graph_objects as go
import plotly.express as px
import matplotlib.pyplot as plt

In [ ]:
modi = pd.read_csv(r"/content/modi_reviews.csv")
rahul = pd.read_csv(r"/content/rahul_reviews.csv")

In [ ]:
modi.head(5)

,Unnamed: 0,User,Tweet
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...
3,3,TheNirbhay1,PM Modi creates a new record of being the only...
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...

In [ ]:
modi.shape

(25688, 3)

In [ ]:
rahul.shape

(14261, 3)

In [ ]:
# Sentiment Analysis
# Now, I will get started with sentiment analysis. I will do it by using the Textblob package in Python. Here I will use this package to perform simple text classification in either positive or negative on the basis of sentiment analysis:

# 1 Polarity refers to the sentiment or emotion expressed in the text, ranging from negative to positive.

# 2 Subjectivity,suggests that the text contains some subjects or opinions, measures the extent to which the text is subjective or opinionated rather than objective

In [ ]:
textblob1 = TextBlob(modi['Tweet'][12])
textblob1.sentiment
textblob2 = TextBlob(rahul['Tweet'][200])
textblob2.sentiment

Sentiment(polarity=-0.3666666666666667, subjectivity=0.43333333333333335)

In [ ]:
def find_pol(review):
  return TextBlob(review).sentiment.polarity

In [ ]:
modi['Sentiment Polarity'] = modi['Tweet'].astype(str).apply(find_pol)
rahul['Sentiment Polarity'] = rahul['Tweet'].astype(str).apply(find_pol)

In [ ]:
modi.head(3)

,Unnamed: 0,User,Tweet,Sentiment Polarity
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...,0.35
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...,0.80
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...,0.80

In [ ]:
rahul.head(3)

,Unnamed: 0,User,Tweet,Sentiment Polarity
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...,0.21875
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...,0.00000
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...,0.00000

In [ ]:
# Sentiment Polarity on Both the candidates:
# Now I will add a new attribute in both the datasets by the name of “Expression Label”:
# 1 polarity > 0 :: positive
# 2 polarity < 0 :: negative
# 3 Polarity == 0 :: neutral

In [ ]:
modi['Expression label'] = np.where(modi['Sentiment Polarity']>0, 'positive', 'negative')
modi['Expression label'][modi['Sentiment Polarity']==0]=="Neutral"
print(modi.tail())

rahul['Expression label'] = np.where(rahul['Sentiment Polarity']>0, 'positive', 'negative')
rahul['Expression label'][rahul['Sentiment Polarity']==0]=="Neutral"
print(rahul.tail())

       Unnamed: 0           User  \
25683       25683     shv_indian
25684       25684     SONUPINKOO
25685       25685     SONUPINKOO
25686       25686     SONUPINKOO
25687       25687  parthajit0101

                                                   Tweet  Sentiment Polarity  \
25683  #1DDrive #ModiSpeaksToNews18 #LokSabhaElection...            0.000000
25684  I am seriously worried about future of Indian ...            0.209524
25685  If @narendramodi is so Bad then Why does @INCI...           -0.700000
25686  On this 23rd March (Pakistan Day), I Urge all ...            0.000000
25687  @timesofindia #ArvindKejriwal, #AAP sirji pls ...           -0.213542

      Expression label
25683         negative
25684         positive
25685         negative
25686         negative
25687         negative
       Unnamed: 0        User  \
14256       14256    SunjayJK
14257       14257    SunjayJK
14258       14258  RAMANKAIRA
14259       14259  RAMANKAIRA
14260       14260  RAMANKAIRA

                                                   Tweet  Sentiment Polarity  \
14256  @quizzicalguy In this #LokSabhaElections2019, ...                0.00
14257  @AnumaVidisha @RahulGandhi @ArvindKejriwal whe...               -0.50
14258  @sherryontopp Early morning #political move af...                0.08
14259  @mayankgandhi04 @mallesh_2004 Early morning #p...                0.08
14260  @DrKumarVishwas Early morning #political move ...                0.08

      Expression label
14256         negative
14257         negative
14258         positive
14259         positive
14260         positive

In [ ]:
neutral_modi = modi[modi['Sentiment Polarity']==0.0000]

remove_neutral_modi = modi['Sentiment Polarity'].isin(neutral_modi['Sentiment Polarity'])
modi.drop(modi[remove_neutral_modi].index, inplace=True)

In [ ]:
print(neutral_modi.shape)
print(modi.shape)

(8206, 5)
(17482, 5)

In [ ]:
neutral_rahul = rahul[rahul['Sentiment Polarity']==0.0000]

remove_neutral_rahul = rahul['Sentiment Polarity'].isin(neutral_rahul['Sentiment Polarity'])
rahul.drop(rahul[remove_neutral_rahul].index, inplace=True)

In [ ]:
print(neutral_rahul.shape)
print(rahul.shape)

(4894, 5)
(9367, 5)

In [ ]:
# balance both the datasets
#modi
np.random.seed(10)
remove_n = 8482
drop_indices = np.random.choice(modi.index, remove_n, replace=False)
df_subset_modi = modi.drop(drop_indices)
print(df_subset_modi.shape)

(9000, 5)

In [ ]:
np.random.seed(10)
remove_n = 367
drop_indices = np.random.choice(rahul.index, remove_n, replace=False)
df_subset_rahul = rahul.drop(drop_indices)
print(df_subset_rahul.shape)

(9000, 5)

In [ ]:
#Both modi and rahul are equal data is balace now.

In [ ]:
#Predict the India Elections, by analyzing the number of positive and negative sentiments in both the accounts:

In [ ]:
count_1 = df_subset_modi.groupby('Expression label').count()
print(count_1)
negative_per1 = (count_1['Sentiment Polarity'][0]/1000)*100
positive_per1 = (count_1['Sentiment Polarity'][1]/1000)*100

count_2 = df_subset_rahul.groupby('Expression label').count()
print(count_2)
negative_per2 = (count_2['Sentiment Polarity'][0]/1000)*100
positive_per2 = (count_2['Sentiment Polarity'][1]/1000)*100

                  Unnamed: 0  User  Tweet  Sentiment Polarity
Expression label
negative                2629  2629   2629                2629
positive                6371  6371   6371                6371
                  Unnamed: 0  User  Tweet  Sentiment Polarity
Expression label
negative                3042  3042   3042                3042
positive                5958  5958   5958                5958

/tmp/ipython-input-165249539.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  negative_per1 = (count_1['Sentiment Polarity'][0]/1000)*100
/tmp/ipython-input-165249539.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  positive_per1 = (count_1['Sentiment Polarity'][1]/1000)*100
/tmp/ipython-input-165249539.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  negative_per2 = (count_2['Sentiment Polarity'][0]/1000)*100
/tmp/ipython-input-165249539.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  positive_per2 = (count_2['Sentiment Polarity'][1]/1000)*100

In [ ]:
#plotting column graph for visual analysis


Politicians = ['modi', 'rahul']
lis_pos = [positive_per1, positive_per2]
lis_neg = [negative_per1, negative_per2]

fig = go.Figure(data=[
    go.Bar(name='Positive', x=Politicians, y=lis_pos),
    go.Bar(name='Negative', x=Politicians, y=lis_neg)
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.show()